### PR TITLE
shut up hayt

### PR DESCRIPTION
**Pull request by justinwoo**

### CODE REVIEW

**Comment by sshirokov** [comment]
I have no idea how I feel about this :(

```
<@> On one hand, it's the most annoying thing since an itchy ballsack
[...]
<@> On the other, it's hilarious how upset people get about it
```

:crying_cat_face: 

cc/ @desert-planet/fremen -- Thoughts?

**Comment by skalnik** [comment]
We should listen to everything the ghola says since he may reveal his true intentions.

**Comment by BeefKnuckleback** [comment]
I'm kinda with skalnik on this one.  Keep it; maybe make it semi-random?

**Comment by sshirokov** [comment]
cc/ #110

**Comment by jensechu** [comment]
It doesn't annoy me at all. I don't see an issue with keeping the greetings.

**Comment by mbulmer** [comment]
Already suggested this in https://github.com/desert-planet/arrakis-hubot/issues/110 - although suppressing the greetings to once daily rather than removing it entirely.

**Comment by skalnik** [comment]
.vote no

**Comment by jensechu** [comment]
.vote no

**Comment by BeefKnuckleback** [comment]
Once daily period or once daily per handle?

**Comment by jensechu** [comment]
Is this *really* that annoying that we need to implement time logic into him?

**Comment by mbulmer** [comment]
For most of us, no, plus the annoyance provides entertainment for others.

**Comment by BeefKnuckleback** [comment]
Annoyance makes the internet go 'round. :heart:

**Comment by sshirokov** [comment]
The desert has spoken, and said ":fu:"

Closing this until a bold programmer armed with `>`, `<`, and `-` can implement time of day guards. :trollface:

**Pull request closed without merging**
