### PR TITLE
Added avatar

### PR DESCRIPTION
**Pull request by elg3cko**
A png of a dead lizard.

### CODE REVIEW

**Comment by Drewzar** [comment]
L:eyes:Ks like a thing.

**Comment by Drewzar** [comment]
I think we need to have @BeefKnuckleback approve though? 

I DON'T KNOW HOW THIS SHIT WORKS.

**Comment by sshirokov** [comment]
Does it meet all the reqs in the README and follow the templates in https://github.com/desert-planet/arrakis-hubot/tree/master/ayp-template-images/ayp-templates :question:

**Comment by elg3cko** [comment]
ALMOST! It does now, Im closing this request and creating one that meets all reqs.

**Pull request closed without merging**
